module.exports = {
  plugins: {
    "postcss-preset-mantine": {},
    "postcss-simple-vars": {
      variables: {
        "mantine-breakpoint-xs": "36em",
        "mantine-breakpoint-sm": "48em",
        "mantine-breakpoint-md": "62em",
        "mantine-breakpoint-lg": "75em",
        "mantine-breakpoint-xl": "88em",
        "c-blue-0": "--mantine-color-blue-0", // #4DFFFF
        "c-blue-1": "--mantine-color-blue-1", // #41FDFF
        "c-blue-2": "--mantine-color-blue-2", // #3AEBFD
        "c-blue-3": "--mantine-color-blue-3", // #33D9F8
        "c-blue-4": "--mantine-color-blue-4", // #2DC7F3
        "c-blue-5": "--mantine-color-blue-5", // #1C7BB2
        "c-blue-6": "--mantine-color-blue-6", // #186CA6
        "c-blue-7": "--mantine-color-blue-7", // #145D9A
        "c-blue-8": "--mantine-color-blue-8", // #104E8E
        "c-blue-9": "--mantine-color-blue-9", // #0D3F82
        "c-dark-0": "--mantine-color-dark-0", // #C1C2C5
        "c-dark-1": "--mantine-color-dark-1", // #909296
        "c-dark-2": "--mantine-color-dark-2", // #5C5F66
        "c-dark-3": "--mantine-color-dark-3", // #373A40
        "c-dark-4": "--mantine-color-dark-4", // #131314
        "c-dark-5": "--mantine-color-dark-5", // #101113
        "c-dark-6": "--mantine-color-dark-6", // #0b0c0d
        "c-dark-7": "--mantine-color-dark-7", // #050506
        "c-dark-8": "--mantine-color-dark-8", // #020202
        "c-dark-9": "--mantine-color-dark-9", // #010101
        "c-red-0": "--mantine-color-red-0",
        "c-red-1": "--mantine-color-red-1",
        "c-red-2": "--mantine-color-red-2",
        "c-red-3": "--mantine-color-red-3",
        "c-red-4": "--mantine-color-red-4",
        "c-red-5": "--mantine-color-red-5",
        "c-red-6": "--mantine-color-red-6",
        "c-red-7": "--mantine-color-red-7",
        "c-red-8": "--mantine-color-red-8",
        "c-red-9": "--mantine-color-red-9",
        "c-green-0": "--mantine-color-green-0",
        "c-green-1": "--mantine-color-green-1",
        "c-green-2": "--mantine-color-green-2",
        "c-green-3": "--mantine-color-green-3",
        "c-green-4": "--mantine-color-green-4",
        "c-green-5": "--mantine-color-green-5",
        "c-green-6": "--mantine-color-green-6",
        "c-green-7": "--mantine-color-green-7",
        "c-green-8": "--mantine-color-green-8",
        "c-green-9": "--mantine-color-green-9",
        "c-yellow-0": "--mantine-color-yellow-0",
        "c-yellow-1": "--mantine-color-yellow-1",
        "c-yellow-2": "--mantine-color-yellow-2",
        "c-yellow-3": "--mantine-color-yellow-3",
        "c-yellow-4": "--mantine-color-yellow-4",
        "c-yellow-5": "--mantine-color-yellow-5",
        "c-yellow-6": "--mantine-color-yellow-6",
        "c-yellow-7": "--mantine-color-yellow-7",
        "c-yellow-8": "--mantine-color-yellow-8",
        "c-yellow-9": "--mantine-color-yellow-9",
        "c-orange-0": "--mantine-color-orange-0",
        "c-orange-1": "--mantine-color-orange-1",
        "c-orange-2": "--mantine-color-orange-2",
        "c-orange-3": "--mantine-color-orange-3",
        "c-orange-4": "--mantine-color-orange-4",
        "c-orange-5": "--mantine-color-orange-5",
        "c-orange-6": "--mantine-color-orange-6",
        "c-orange-7": "--mantine-color-orange-7",
        "c-orange-8": "--mantine-color-orange-8",
        "c-orange-9": "--mantine-color-orange-9",
        "c-purple-0": "--mantine-color-purple-0",
        "c-purple-1": "--mantine-color-purple-1",
        "c-purple-2": "--mantine-color-purple-2",
        "c-purple-3": "--mantine-color-purple-3",
        "c-purple-4": "--mantine-color-purple-4",
        "c-purple-5": "--mantine-color-purple-5",
        "c-purple-6": "--mantine-color-purple-6",
        "c-purple-7": "--mantine-color-purple-7",
        "c-purple-8": "--mantine-color-purple-8",
        "c-purple-9": "--mantine-color-purple-9",
        "c-pink-0": "--mantine-color-pink-0",
        "c-pink-1": "--mantine-color-pink-1",
        "c-pink-2": "--mantine-color-pink-2",
        "c-pink-3": "--mantine-color-pink-3",
        "c-pink-4": "--mantine-color-pink-4",
        "c-pink-5": "--mantine-color-pink-5",
        "c-pink-6": "--mantine-color-pink-6",
        "c-pink-7": "--mantine-color-pink-7",
        "c-pink-8": "--mantine-color-pink-8",
        "c-pink-9": "--mantine-color-pink-9",
        "c-teal-0": "--mantine-color-teal-0",
        "c-teal-1": "--mantine-color-teal-1",
        "c-teal-2": "--mantine-color-teal-2",
        "c-teal-3": "--mantine-color-teal-3",
        "c-teal-4": "--mantine-color-teal-4",
        "c-teal-5": "--mantine-color-teal-5",
        "c-teal-6": "--mantine-color-teal-6",
        "c-teal-7": "--mantine-color-teal-7",
        "c-teal-8": "--mantine-color-teal-8",
        "c-teal-9": "--mantine-color-teal-9",
        "c-cyan-0": "--mantine-color-cyan-0",
        "c-cyan-1": "--mantine-color-cyan-1",
        "c-cyan-2": "--mantine-color-cyan-2",
        "c-cyan-3": "--mantine-color-cyan-3",
        "c-cyan-4": "--mantine-color-cyan-4",
        "c-cyan-5": "--mantine-color-cyan-5",
        "c-cyan-6": "--mantine-color-cyan-6",
        "c-cyan-7": "--mantine-color-cyan-7",
        "c-cyan-8": "--mantine-color-cyan-8",
        "c-cyan-9": "--mantine-color-cyan-9",
        "c-gray-0": "--mantine-color-gray-0",
        "c-gray-1": "--mantine-color-gray-1",
        "c-gray-2": "--mantine-color-gray-2",
        "c-gray-3": "--mantine-color-gray-3",
        "c-gray-4": "--mantine-color-gray-4",
        "c-gray-5": "--mantine-color-gray-5",
        "c-gray-6": "--mantine-color-gray-6",
        "c-gray-7": "--mantine-color-gray-7",
        "c-gray-8": "--mantine-color-gray-8",
        "c-gray-9": "--mantine-color-gray-9",
        "c-grape-0": "--mantine-color-grape-0",
        "c-grape-1": "--mantine-color-grape-1",
        "c-grape-2": "--mantine-color-grape-2",
        "c-grape-3": "--mantine-color-grape-3",
        "c-grape-4": "--mantine-color-grape-4",
        "c-grape-5": "--mantine-color-grape-5",
        "c-grape-6": "--mantine-color-grape-6",
        "c-grape-7": "--mantine-color-grape-7",
        "c-grape-8": "--mantine-color-grape-8",
        "c-grape-9": "--mantine-color-grape-9",
        "c-violet-0": "--mantine-color-violet-0",
        "c-violet-1": "--mantine-color-violet-1",
        "c-violet-2": "--mantine-color-violet-2",
        "c-violet-3": "--mantine-color-violet-3",
        "c-violet-4": "--mantine-color-violet-4",
        "c-violet-5": "--mantine-color-violet-5",
        "c-violet-6": "--mantine-color-violet-6",
        "c-violet-7": "--mantine-color-violet-7",
        "c-violet-8": "--mantine-color-violet-8",
        "c-violet-9": "--mantine-color-violet-9",
        "c-indigo-0": "--mantine-color-indigo-0",
        "c-indigo-1": "--mantine-color-indigo-1",
        "c-indigo-2": "--mantine-color-indigo-2",
        "c-indigo-3": "--mantine-color-indigo-3",
        "c-indigo-4": "--mantine-color-indigo-4",
        "c-indigo-5": "--mantine-color-indigo-5",
        "c-indigo-6": "--mantine-color-indigo-6",
        "c-indigo-7": "--mantine-color-indigo-7",
        "c-indigo-8": "--mantine-color-indigo-8",
        "c-indigo-9": "--mantine-color-indigo-9",
        "c-lime-0": "--mantine-color-lime-0",
        "c-lime-1": "--mantine-color-lime-1",
        "c-lime-2": "--mantine-color-lime-2",
        "c-lime-3": "--mantine-color-lime-3",
        "c-lime-4": "--mantine-color-lime-4",
        "c-lime-5": "--mantine-color-lime-5",
        "c-lime-6": "--mantine-color-lime-6",
        "c-lime-7": "--mantine-color-lime-7",
        "c-lime-8": "--mantine-color-lime-8",
        "c-lime-9": "--mantine-color-lime-9",
      },
    },
  },
};
