version: "3"
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - ./:/tourassist
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
