name: Tourassist Docker Build and Push

on:
  push:
    branches:
      - master  # Trigger on push to master branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.zenneson }}
        password: ${{ secrets.process.env.NEXT_PUBLIC_DOCKER_HUB_ACCESS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: zenneson/tourassist:latest
